---
- name: comcast - install
  hosts: all
  tags: comcast_install

  vars:
    go_gopath: "/opt/golang"
    comcast_pkg: "github.com/tylertreat/comcast"

  tasks:
    - name: install git
      apt:
        pkg: git
        update_cache: yes
        cache_valid_time: 3600
        state: installed
      become: yes

    - name: install go
      apt:
        pkg: golang
        update_cache: yes
        cache_valid_time: 3600
        state: installed
      become: yes

    - name: set GOPATH
      lineinfile:
        dest: /etc/environment
        line: "GOPATH=\"{{ go_gopath }}\""
        insertafter: EOF
        regexp: "^GOPATH=\"{{ go_gopath }}\"$"
        state: present
      become: yes

    - name: install comcast
      command: go get {{ comcast_pkg }}
      args:
        creates: "{{ go_gopath }}/pkg/linux_amd64/{{ comcast_pkg }}"
      environment:
        GOPATH: "{{ go_gopath }}"
      become: yes

- name: comcast - packet loss
  hosts: all
  tags: comcast_packet_loss

  vars:
    go_gopath: "/opt/golang"

  tasks:
    - name: comcast - set packet loss
      command: "{{ go_gopath }}/bin/comcast --device eth1 --packet-loss 100%"
      become: yes

    - name: comcast - wait for user
      pause:
        prompt: Ready when you are...

    - name: comcast - reset packet loss
      command: "{{ go_gopath }}/bin/comcast --device eth1 --mode stop"
      become: yes

