---
- name: rabbitmq high availability
  hosts: all

  pre_tasks:
    - name: hosts - add names to /etc/hosts
      lineinfile:
        dest: /etc/hosts
        line: "{{ hostvars[item].ansible_eth1.ipv4.address }} {{ hostvars[item].ansible_hostname }}"
        insertafter: EOF
        regexp: "^{{ hostvars[item].ansible_eth1.ipv4.address }} {{ hostvars[item].ansible_hostname }}$"
        state: present
      with_items: groups['all']
      become: yes
      tags: hosts

  roles:
    - role: mtpereira.erlang
      become: yes
      tags: erlang
    - role: alexeymedvedchikov.rabbitmq
      become: yes
      tags: rabbitmq-cluster
